name: mlagents_3.10
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cccl=12.3.101
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.3.101
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.1.0
  - filelock=3.13.1
  - freetype=2.12.1
  - gmpy2=2.1.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.3
  - jpeg=9e
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - networkx=3.1
  - numpy=1.21.2
  - numpy-base=1.21.2
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - python=3.10.12
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - typing_extensions=4.9.0
  - tzdata=2023d
  - urllib3=2.1.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - absl-py==2.1.0
    - attrs==23.2.0
    - cattrs==1.5.0
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - fsspec==2024.2.0
    - grpcio==1.48.2
    - gym==0.26.2
    - gym-notices==0.0.8
    - h5py==3.10.0
    - huggingface-hub==0.20.3
    - markdown==3.5.2
    - mlagents==1.0.0
    - mlagents-envs==1.0.0
    - onnx==1.12.0
    - packaging==23.2
    - pettingzoo==1.15.0
    - pip==24.0
    - protobuf==3.19.6
    - pypiwin32==223
    - pywin32==306
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - torchaudio==2.2.0
    - torchvision==0.17.0
    - tqdm==4.66.2
    - werkzeug==3.0.1
